import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="my-8 mx-6">
          <Navbar />
        </div>
        {children}
        <footer className="absolute bottom-2 flex justify-center gap-10 items-center w-[100%] text-gray-300">
          <p>Zakat calculation</p>
          <p>Copyright©2024</p>
        </footer>
      </body>
    </html>
  );
}
